# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/vjiaoblack/Compsci/clion-2018.1.2/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/vjiaoblack/Compsci/clion-2018.1.2/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vjiaoblack/Compsci/Athena

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vjiaoblack/Compsci/Athena

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/vjiaoblack/Compsci/clion-2018.1.2/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/vjiaoblack/Compsci/clion-2018.1.2/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vjiaoblack/Compsci/Athena/CMakeFiles /home/vjiaoblack/Compsci/Athena/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vjiaoblack/Compsci/Athena/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Athena

# Build rule for target.
Athena: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Athena
.PHONY : Athena

# fast build rule for target.
Athena/fast:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/build
.PHONY : Athena/fast

src/Perlin.o: src/Perlin.cpp.o

.PHONY : src/Perlin.o

# target to build an object file
src/Perlin.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/Perlin.cpp.o
.PHONY : src/Perlin.cpp.o

src/Perlin.i: src/Perlin.cpp.i

.PHONY : src/Perlin.i

# target to preprocess a source file
src/Perlin.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/Perlin.cpp.i
.PHONY : src/Perlin.cpp.i

src/Perlin.s: src/Perlin.cpp.s

.PHONY : src/Perlin.s

# target to generate assembly for a file
src/Perlin.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/Perlin.cpp.s
.PHONY : src/Perlin.cpp.s

src/TrData/TrData.o: src/TrData/TrData.cpp.o

.PHONY : src/TrData/TrData.o

# target to build an object file
src/TrData/TrData.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrData/TrData.cpp.o
.PHONY : src/TrData/TrData.cpp.o

src/TrData/TrData.i: src/TrData/TrData.cpp.i

.PHONY : src/TrData/TrData.i

# target to preprocess a source file
src/TrData/TrData.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrData/TrData.cpp.i
.PHONY : src/TrData/TrData.cpp.i

src/TrData/TrData.s: src/TrData/TrData.cpp.s

.PHONY : src/TrData/TrData.s

# target to generate assembly for a file
src/TrData/TrData.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrData/TrData.cpp.s
.PHONY : src/TrData/TrData.cpp.s

src/TrECS/TrFormulas/TrFormula.o: src/TrECS/TrFormulas/TrFormula.cpp.o

.PHONY : src/TrECS/TrFormulas/TrFormula.o

# target to build an object file
src/TrECS/TrFormulas/TrFormula.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrFormulas/TrFormula.cpp.o
.PHONY : src/TrECS/TrFormulas/TrFormula.cpp.o

src/TrECS/TrFormulas/TrFormula.i: src/TrECS/TrFormulas/TrFormula.cpp.i

.PHONY : src/TrECS/TrFormulas/TrFormula.i

# target to preprocess a source file
src/TrECS/TrFormulas/TrFormula.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrFormulas/TrFormula.cpp.i
.PHONY : src/TrECS/TrFormulas/TrFormula.cpp.i

src/TrECS/TrFormulas/TrFormula.s: src/TrECS/TrFormulas/TrFormula.cpp.s

.PHONY : src/TrECS/TrFormulas/TrFormula.s

# target to generate assembly for a file
src/TrECS/TrFormulas/TrFormula.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrFormulas/TrFormula.cpp.s
.PHONY : src/TrECS/TrFormulas/TrFormula.cpp.s

src/TrECS/TrItems/TrItem.o: src/TrECS/TrItems/TrItem.cpp.o

.PHONY : src/TrECS/TrItems/TrItem.o

# target to build an object file
src/TrECS/TrItems/TrItem.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrItems/TrItem.cpp.o
.PHONY : src/TrECS/TrItems/TrItem.cpp.o

src/TrECS/TrItems/TrItem.i: src/TrECS/TrItems/TrItem.cpp.i

.PHONY : src/TrECS/TrItems/TrItem.i

# target to preprocess a source file
src/TrECS/TrItems/TrItem.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrItems/TrItem.cpp.i
.PHONY : src/TrECS/TrItems/TrItem.cpp.i

src/TrECS/TrItems/TrItem.s: src/TrECS/TrItems/TrItem.cpp.s

.PHONY : src/TrECS/TrItems/TrItem.s

# target to generate assembly for a file
src/TrECS/TrItems/TrItem.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrItems/TrItem.cpp.s
.PHONY : src/TrECS/TrItems/TrItem.cpp.s

src/TrECS/TrSystems/TrEntitySystem.o: src/TrECS/TrSystems/TrEntitySystem.cpp.o

.PHONY : src/TrECS/TrSystems/TrEntitySystem.o

# target to build an object file
src/TrECS/TrSystems/TrEntitySystem.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrSystems/TrEntitySystem.cpp.o
.PHONY : src/TrECS/TrSystems/TrEntitySystem.cpp.o

src/TrECS/TrSystems/TrEntitySystem.i: src/TrECS/TrSystems/TrEntitySystem.cpp.i

.PHONY : src/TrECS/TrSystems/TrEntitySystem.i

# target to preprocess a source file
src/TrECS/TrSystems/TrEntitySystem.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrSystems/TrEntitySystem.cpp.i
.PHONY : src/TrECS/TrSystems/TrEntitySystem.cpp.i

src/TrECS/TrSystems/TrEntitySystem.s: src/TrECS/TrSystems/TrEntitySystem.cpp.s

.PHONY : src/TrECS/TrSystems/TrEntitySystem.s

# target to generate assembly for a file
src/TrECS/TrSystems/TrEntitySystem.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrECS/TrSystems/TrEntitySystem.cpp.s
.PHONY : src/TrECS/TrSystems/TrEntitySystem.cpp.s

src/TrGUI/TrGUIButton.o: src/TrGUI/TrGUIButton.cpp.o

.PHONY : src/TrGUI/TrGUIButton.o

# target to build an object file
src/TrGUI/TrGUIButton.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIButton.cpp.o
.PHONY : src/TrGUI/TrGUIButton.cpp.o

src/TrGUI/TrGUIButton.i: src/TrGUI/TrGUIButton.cpp.i

.PHONY : src/TrGUI/TrGUIButton.i

# target to preprocess a source file
src/TrGUI/TrGUIButton.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIButton.cpp.i
.PHONY : src/TrGUI/TrGUIButton.cpp.i

src/TrGUI/TrGUIButton.s: src/TrGUI/TrGUIButton.cpp.s

.PHONY : src/TrGUI/TrGUIButton.s

# target to generate assembly for a file
src/TrGUI/TrGUIButton.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIButton.cpp.s
.PHONY : src/TrGUI/TrGUIButton.cpp.s

src/TrGUI/TrGUIDropdownMenu.o: src/TrGUI/TrGUIDropdownMenu.cpp.o

.PHONY : src/TrGUI/TrGUIDropdownMenu.o

# target to build an object file
src/TrGUI/TrGUIDropdownMenu.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIDropdownMenu.cpp.o
.PHONY : src/TrGUI/TrGUIDropdownMenu.cpp.o

src/TrGUI/TrGUIDropdownMenu.i: src/TrGUI/TrGUIDropdownMenu.cpp.i

.PHONY : src/TrGUI/TrGUIDropdownMenu.i

# target to preprocess a source file
src/TrGUI/TrGUIDropdownMenu.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIDropdownMenu.cpp.i
.PHONY : src/TrGUI/TrGUIDropdownMenu.cpp.i

src/TrGUI/TrGUIDropdownMenu.s: src/TrGUI/TrGUIDropdownMenu.cpp.s

.PHONY : src/TrGUI/TrGUIDropdownMenu.s

# target to generate assembly for a file
src/TrGUI/TrGUIDropdownMenu.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIDropdownMenu.cpp.s
.PHONY : src/TrGUI/TrGUIDropdownMenu.cpp.s

src/TrGUI/TrGUIMenu.o: src/TrGUI/TrGUIMenu.cpp.o

.PHONY : src/TrGUI/TrGUIMenu.o

# target to build an object file
src/TrGUI/TrGUIMenu.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIMenu.cpp.o
.PHONY : src/TrGUI/TrGUIMenu.cpp.o

src/TrGUI/TrGUIMenu.i: src/TrGUI/TrGUIMenu.cpp.i

.PHONY : src/TrGUI/TrGUIMenu.i

# target to preprocess a source file
src/TrGUI/TrGUIMenu.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIMenu.cpp.i
.PHONY : src/TrGUI/TrGUIMenu.cpp.i

src/TrGUI/TrGUIMenu.s: src/TrGUI/TrGUIMenu.cpp.s

.PHONY : src/TrGUI/TrGUIMenu.s

# target to generate assembly for a file
src/TrGUI/TrGUIMenu.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIMenu.cpp.s
.PHONY : src/TrGUI/TrGUIMenu.cpp.s

src/TrGUI/TrGUITextBox.o: src/TrGUI/TrGUITextBox.cpp.o

.PHONY : src/TrGUI/TrGUITextBox.o

# target to build an object file
src/TrGUI/TrGUITextBox.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUITextBox.cpp.o
.PHONY : src/TrGUI/TrGUITextBox.cpp.o

src/TrGUI/TrGUITextBox.i: src/TrGUI/TrGUITextBox.cpp.i

.PHONY : src/TrGUI/TrGUITextBox.i

# target to preprocess a source file
src/TrGUI/TrGUITextBox.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUITextBox.cpp.i
.PHONY : src/TrGUI/TrGUITextBox.cpp.i

src/TrGUI/TrGUITextBox.s: src/TrGUI/TrGUITextBox.cpp.s

.PHONY : src/TrGUI/TrGUITextBox.s

# target to generate assembly for a file
src/TrGUI/TrGUITextBox.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUITextBox.cpp.s
.PHONY : src/TrGUI/TrGUITextBox.cpp.s

src/TrGUI/TrGUIWindow.o: src/TrGUI/TrGUIWindow.cpp.o

.PHONY : src/TrGUI/TrGUIWindow.o

# target to build an object file
src/TrGUI/TrGUIWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIWindow.cpp.o
.PHONY : src/TrGUI/TrGUIWindow.cpp.o

src/TrGUI/TrGUIWindow.i: src/TrGUI/TrGUIWindow.cpp.i

.PHONY : src/TrGUI/TrGUIWindow.i

# target to preprocess a source file
src/TrGUI/TrGUIWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIWindow.cpp.i
.PHONY : src/TrGUI/TrGUIWindow.cpp.i

src/TrGUI/TrGUIWindow.s: src/TrGUI/TrGUIWindow.cpp.s

.PHONY : src/TrGUI/TrGUIWindow.s

# target to generate assembly for a file
src/TrGUI/TrGUIWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGUI/TrGUIWindow.cpp.s
.PHONY : src/TrGUI/TrGUIWindow.cpp.s

src/TrGame.o: src/TrGame.cpp.o

.PHONY : src/TrGame.o

# target to build an object file
src/TrGame.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGame.cpp.o
.PHONY : src/TrGame.cpp.o

src/TrGame.i: src/TrGame.cpp.i

.PHONY : src/TrGame.i

# target to preprocess a source file
src/TrGame.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGame.cpp.i
.PHONY : src/TrGame.cpp.i

src/TrGame.s: src/TrGame.cpp.s

.PHONY : src/TrGame.s

# target to generate assembly for a file
src/TrGame.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGame.cpp.s
.PHONY : src/TrGame.cpp.s

src/TrGraphics.o: src/TrGraphics.cpp.o

.PHONY : src/TrGraphics.o

# target to build an object file
src/TrGraphics.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGraphics.cpp.o
.PHONY : src/TrGraphics.cpp.o

src/TrGraphics.i: src/TrGraphics.cpp.i

.PHONY : src/TrGraphics.i

# target to preprocess a source file
src/TrGraphics.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGraphics.cpp.i
.PHONY : src/TrGraphics.cpp.i

src/TrGraphics.s: src/TrGraphics.cpp.s

.PHONY : src/TrGraphics.s

# target to generate assembly for a file
src/TrGraphics.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrGraphics.cpp.s
.PHONY : src/TrGraphics.cpp.s

src/TrMap/TrColorMap.o: src/TrMap/TrColorMap.cpp.o

.PHONY : src/TrMap/TrColorMap.o

# target to build an object file
src/TrMap/TrColorMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrColorMap.cpp.o
.PHONY : src/TrMap/TrColorMap.cpp.o

src/TrMap/TrColorMap.i: src/TrMap/TrColorMap.cpp.i

.PHONY : src/TrMap/TrColorMap.i

# target to preprocess a source file
src/TrMap/TrColorMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrColorMap.cpp.i
.PHONY : src/TrMap/TrColorMap.cpp.i

src/TrMap/TrColorMap.s: src/TrMap/TrColorMap.cpp.s

.PHONY : src/TrMap/TrColorMap.s

# target to generate assembly for a file
src/TrMap/TrColorMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrColorMap.cpp.s
.PHONY : src/TrMap/TrColorMap.cpp.s

src/TrMap/TrHeightMap.o: src/TrMap/TrHeightMap.cpp.o

.PHONY : src/TrMap/TrHeightMap.o

# target to build an object file
src/TrMap/TrHeightMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrHeightMap.cpp.o
.PHONY : src/TrMap/TrHeightMap.cpp.o

src/TrMap/TrHeightMap.i: src/TrMap/TrHeightMap.cpp.i

.PHONY : src/TrMap/TrHeightMap.i

# target to preprocess a source file
src/TrMap/TrHeightMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrHeightMap.cpp.i
.PHONY : src/TrMap/TrHeightMap.cpp.i

src/TrMap/TrHeightMap.s: src/TrMap/TrHeightMap.cpp.s

.PHONY : src/TrMap/TrHeightMap.s

# target to generate assembly for a file
src/TrMap/TrHeightMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrHeightMap.cpp.s
.PHONY : src/TrMap/TrHeightMap.cpp.s

src/TrMap/TrMap.o: src/TrMap/TrMap.cpp.o

.PHONY : src/TrMap/TrMap.o

# target to build an object file
src/TrMap/TrMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMap.cpp.o
.PHONY : src/TrMap/TrMap.cpp.o

src/TrMap/TrMap.i: src/TrMap/TrMap.cpp.i

.PHONY : src/TrMap/TrMap.i

# target to preprocess a source file
src/TrMap/TrMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMap.cpp.i
.PHONY : src/TrMap/TrMap.cpp.i

src/TrMap/TrMap.s: src/TrMap/TrMap.cpp.s

.PHONY : src/TrMap/TrMap.s

# target to generate assembly for a file
src/TrMap/TrMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMap.cpp.s
.PHONY : src/TrMap/TrMap.cpp.s

src/TrMap/TrMapDataUtils.o: src/TrMap/TrMapDataUtils.cpp.o

.PHONY : src/TrMap/TrMapDataUtils.o

# target to build an object file
src/TrMap/TrMapDataUtils.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMapDataUtils.cpp.o
.PHONY : src/TrMap/TrMapDataUtils.cpp.o

src/TrMap/TrMapDataUtils.i: src/TrMap/TrMapDataUtils.cpp.i

.PHONY : src/TrMap/TrMapDataUtils.i

# target to preprocess a source file
src/TrMap/TrMapDataUtils.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMapDataUtils.cpp.i
.PHONY : src/TrMap/TrMapDataUtils.cpp.i

src/TrMap/TrMapDataUtils.s: src/TrMap/TrMapDataUtils.cpp.s

.PHONY : src/TrMap/TrMapDataUtils.s

# target to generate assembly for a file
src/TrMap/TrMapDataUtils.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMapDataUtils.cpp.s
.PHONY : src/TrMap/TrMapDataUtils.cpp.s

src/TrMap/TrMoistureMap.o: src/TrMap/TrMoistureMap.cpp.o

.PHONY : src/TrMap/TrMoistureMap.o

# target to build an object file
src/TrMap/TrMoistureMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMoistureMap.cpp.o
.PHONY : src/TrMap/TrMoistureMap.cpp.o

src/TrMap/TrMoistureMap.i: src/TrMap/TrMoistureMap.cpp.i

.PHONY : src/TrMap/TrMoistureMap.i

# target to preprocess a source file
src/TrMap/TrMoistureMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMoistureMap.cpp.i
.PHONY : src/TrMap/TrMoistureMap.cpp.i

src/TrMap/TrMoistureMap.s: src/TrMap/TrMoistureMap.cpp.s

.PHONY : src/TrMap/TrMoistureMap.s

# target to generate assembly for a file
src/TrMap/TrMoistureMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrMoistureMap.cpp.s
.PHONY : src/TrMap/TrMoistureMap.cpp.s

src/TrMap/TrNormalMap.o: src/TrMap/TrNormalMap.cpp.o

.PHONY : src/TrMap/TrNormalMap.o

# target to build an object file
src/TrMap/TrNormalMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrNormalMap.cpp.o
.PHONY : src/TrMap/TrNormalMap.cpp.o

src/TrMap/TrNormalMap.i: src/TrMap/TrNormalMap.cpp.i

.PHONY : src/TrMap/TrNormalMap.i

# target to preprocess a source file
src/TrMap/TrNormalMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrNormalMap.cpp.i
.PHONY : src/TrMap/TrNormalMap.cpp.i

src/TrMap/TrNormalMap.s: src/TrMap/TrNormalMap.cpp.s

.PHONY : src/TrMap/TrNormalMap.s

# target to generate assembly for a file
src/TrMap/TrNormalMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrNormalMap.cpp.s
.PHONY : src/TrMap/TrNormalMap.cpp.s

src/TrMap/TrVegetationMap.o: src/TrMap/TrVegetationMap.cpp.o

.PHONY : src/TrMap/TrVegetationMap.o

# target to build an object file
src/TrMap/TrVegetationMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrVegetationMap.cpp.o
.PHONY : src/TrMap/TrVegetationMap.cpp.o

src/TrMap/TrVegetationMap.i: src/TrMap/TrVegetationMap.cpp.i

.PHONY : src/TrMap/TrVegetationMap.i

# target to preprocess a source file
src/TrMap/TrVegetationMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrVegetationMap.cpp.i
.PHONY : src/TrMap/TrVegetationMap.cpp.i

src/TrMap/TrVegetationMap.s: src/TrMap/TrVegetationMap.cpp.s

.PHONY : src/TrMap/TrVegetationMap.s

# target to generate assembly for a file
src/TrMap/TrVegetationMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrVegetationMap.cpp.s
.PHONY : src/TrMap/TrVegetationMap.cpp.s

src/TrMap/TrWaterMap.o: src/TrMap/TrWaterMap.cpp.o

.PHONY : src/TrMap/TrWaterMap.o

# target to build an object file
src/TrMap/TrWaterMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrWaterMap.cpp.o
.PHONY : src/TrMap/TrWaterMap.cpp.o

src/TrMap/TrWaterMap.i: src/TrMap/TrWaterMap.cpp.i

.PHONY : src/TrMap/TrWaterMap.i

# target to preprocess a source file
src/TrMap/TrWaterMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrWaterMap.cpp.i
.PHONY : src/TrMap/TrWaterMap.cpp.i

src/TrMap/TrWaterMap.s: src/TrMap/TrWaterMap.cpp.s

.PHONY : src/TrMap/TrWaterMap.s

# target to generate assembly for a file
src/TrMap/TrWaterMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrWaterMap.cpp.s
.PHONY : src/TrMap/TrWaterMap.cpp.s

src/TrMap/TrWindMap.o: src/TrMap/TrWindMap.cpp.o

.PHONY : src/TrMap/TrWindMap.o

# target to build an object file
src/TrMap/TrWindMap.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrWindMap.cpp.o
.PHONY : src/TrMap/TrWindMap.cpp.o

src/TrMap/TrWindMap.i: src/TrMap/TrWindMap.cpp.i

.PHONY : src/TrMap/TrWindMap.i

# target to preprocess a source file
src/TrMap/TrWindMap.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrWindMap.cpp.i
.PHONY : src/TrMap/TrWindMap.cpp.i

src/TrMap/TrWindMap.s: src/TrMap/TrWindMap.cpp.s

.PHONY : src/TrMap/TrWindMap.s

# target to generate assembly for a file
src/TrMap/TrWindMap.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrMap/TrWindMap.cpp.s
.PHONY : src/TrMap/TrWindMap.cpp.s

src/TrRenderLoop/TrGameLoop.o: src/TrRenderLoop/TrGameLoop.cpp.o

.PHONY : src/TrRenderLoop/TrGameLoop.o

# target to build an object file
src/TrRenderLoop/TrGameLoop.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrGameLoop.cpp.o
.PHONY : src/TrRenderLoop/TrGameLoop.cpp.o

src/TrRenderLoop/TrGameLoop.i: src/TrRenderLoop/TrGameLoop.cpp.i

.PHONY : src/TrRenderLoop/TrGameLoop.i

# target to preprocess a source file
src/TrRenderLoop/TrGameLoop.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrGameLoop.cpp.i
.PHONY : src/TrRenderLoop/TrGameLoop.cpp.i

src/TrRenderLoop/TrGameLoop.s: src/TrRenderLoop/TrGameLoop.cpp.s

.PHONY : src/TrRenderLoop/TrGameLoop.s

# target to generate assembly for a file
src/TrRenderLoop/TrGameLoop.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrGameLoop.cpp.s
.PHONY : src/TrRenderLoop/TrGameLoop.cpp.s

src/TrRenderLoop/TrMainMenuLoop.o: src/TrRenderLoop/TrMainMenuLoop.cpp.o

.PHONY : src/TrRenderLoop/TrMainMenuLoop.o

# target to build an object file
src/TrRenderLoop/TrMainMenuLoop.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrMainMenuLoop.cpp.o
.PHONY : src/TrRenderLoop/TrMainMenuLoop.cpp.o

src/TrRenderLoop/TrMainMenuLoop.i: src/TrRenderLoop/TrMainMenuLoop.cpp.i

.PHONY : src/TrRenderLoop/TrMainMenuLoop.i

# target to preprocess a source file
src/TrRenderLoop/TrMainMenuLoop.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrMainMenuLoop.cpp.i
.PHONY : src/TrRenderLoop/TrMainMenuLoop.cpp.i

src/TrRenderLoop/TrMainMenuLoop.s: src/TrRenderLoop/TrMainMenuLoop.cpp.s

.PHONY : src/TrRenderLoop/TrMainMenuLoop.s

# target to generate assembly for a file
src/TrRenderLoop/TrMainMenuLoop.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrMainMenuLoop.cpp.s
.PHONY : src/TrRenderLoop/TrMainMenuLoop.cpp.s

src/TrRenderLoop/TrTransitionLoop.o: src/TrRenderLoop/TrTransitionLoop.cpp.o

.PHONY : src/TrRenderLoop/TrTransitionLoop.o

# target to build an object file
src/TrRenderLoop/TrTransitionLoop.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrTransitionLoop.cpp.o
.PHONY : src/TrRenderLoop/TrTransitionLoop.cpp.o

src/TrRenderLoop/TrTransitionLoop.i: src/TrRenderLoop/TrTransitionLoop.cpp.i

.PHONY : src/TrRenderLoop/TrTransitionLoop.i

# target to preprocess a source file
src/TrRenderLoop/TrTransitionLoop.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrTransitionLoop.cpp.i
.PHONY : src/TrRenderLoop/TrTransitionLoop.cpp.i

src/TrRenderLoop/TrTransitionLoop.s: src/TrRenderLoop/TrTransitionLoop.cpp.s

.PHONY : src/TrRenderLoop/TrTransitionLoop.s

# target to generate assembly for a file
src/TrRenderLoop/TrTransitionLoop.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrRenderLoop/TrTransitionLoop.cpp.s
.PHONY : src/TrRenderLoop/TrTransitionLoop.cpp.s

src/TrUtils/TrMath.o: src/TrUtils/TrMath.cpp.o

.PHONY : src/TrUtils/TrMath.o

# target to build an object file
src/TrUtils/TrMath.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrUtils/TrMath.cpp.o
.PHONY : src/TrUtils/TrMath.cpp.o

src/TrUtils/TrMath.i: src/TrUtils/TrMath.cpp.i

.PHONY : src/TrUtils/TrMath.i

# target to preprocess a source file
src/TrUtils/TrMath.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrUtils/TrMath.cpp.i
.PHONY : src/TrUtils/TrMath.cpp.i

src/TrUtils/TrMath.s: src/TrUtils/TrMath.cpp.s

.PHONY : src/TrUtils/TrMath.s

# target to generate assembly for a file
src/TrUtils/TrMath.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrUtils/TrMath.cpp.s
.PHONY : src/TrUtils/TrMath.cpp.s

src/TrUtils/TrSimulation.o: src/TrUtils/TrSimulation.cpp.o

.PHONY : src/TrUtils/TrSimulation.o

# target to build an object file
src/TrUtils/TrSimulation.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrUtils/TrSimulation.cpp.o
.PHONY : src/TrUtils/TrSimulation.cpp.o

src/TrUtils/TrSimulation.i: src/TrUtils/TrSimulation.cpp.i

.PHONY : src/TrUtils/TrSimulation.i

# target to preprocess a source file
src/TrUtils/TrSimulation.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrUtils/TrSimulation.cpp.i
.PHONY : src/TrUtils/TrSimulation.cpp.i

src/TrUtils/TrSimulation.s: src/TrUtils/TrSimulation.cpp.s

.PHONY : src/TrUtils/TrSimulation.s

# target to generate assembly for a file
src/TrUtils/TrSimulation.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/TrUtils/TrSimulation.cpp.s
.PHONY : src/TrUtils/TrSimulation.cpp.s

src/Utils.o: src/Utils.cpp.o

.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i

.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s

.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/athena.o: src/athena.cpp.o

.PHONY : src/athena.o

# target to build an object file
src/athena.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/athena.cpp.o
.PHONY : src/athena.cpp.o

src/athena.i: src/athena.cpp.i

.PHONY : src/athena.i

# target to preprocess a source file
src/athena.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/athena.cpp.i
.PHONY : src/athena.cpp.i

src/athena.s: src/athena.cpp.s

.PHONY : src/athena.s

# target to generate assembly for a file
src/athena.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/athena.cpp.s
.PHONY : src/athena.cpp.s

src/fft.o: src/fft.cpp.o

.PHONY : src/fft.o

# target to build an object file
src/fft.cpp.o:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/fft.cpp.o
.PHONY : src/fft.cpp.o

src/fft.i: src/fft.cpp.i

.PHONY : src/fft.i

# target to preprocess a source file
src/fft.cpp.i:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/fft.cpp.i
.PHONY : src/fft.cpp.i

src/fft.s: src/fft.cpp.s

.PHONY : src/fft.s

# target to generate assembly for a file
src/fft.cpp.s:
	$(MAKE) -f CMakeFiles/Athena.dir/build.make CMakeFiles/Athena.dir/src/fft.cpp.s
.PHONY : src/fft.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Athena"
	@echo "... src/Perlin.o"
	@echo "... src/Perlin.i"
	@echo "... src/Perlin.s"
	@echo "... src/TrData/TrData.o"
	@echo "... src/TrData/TrData.i"
	@echo "... src/TrData/TrData.s"
	@echo "... src/TrECS/TrFormulas/TrFormula.o"
	@echo "... src/TrECS/TrFormulas/TrFormula.i"
	@echo "... src/TrECS/TrFormulas/TrFormula.s"
	@echo "... src/TrECS/TrItems/TrItem.o"
	@echo "... src/TrECS/TrItems/TrItem.i"
	@echo "... src/TrECS/TrItems/TrItem.s"
	@echo "... src/TrECS/TrSystems/TrEntitySystem.o"
	@echo "... src/TrECS/TrSystems/TrEntitySystem.i"
	@echo "... src/TrECS/TrSystems/TrEntitySystem.s"
	@echo "... src/TrGUI/TrGUIButton.o"
	@echo "... src/TrGUI/TrGUIButton.i"
	@echo "... src/TrGUI/TrGUIButton.s"
	@echo "... src/TrGUI/TrGUIDropdownMenu.o"
	@echo "... src/TrGUI/TrGUIDropdownMenu.i"
	@echo "... src/TrGUI/TrGUIDropdownMenu.s"
	@echo "... src/TrGUI/TrGUIMenu.o"
	@echo "... src/TrGUI/TrGUIMenu.i"
	@echo "... src/TrGUI/TrGUIMenu.s"
	@echo "... src/TrGUI/TrGUITextBox.o"
	@echo "... src/TrGUI/TrGUITextBox.i"
	@echo "... src/TrGUI/TrGUITextBox.s"
	@echo "... src/TrGUI/TrGUIWindow.o"
	@echo "... src/TrGUI/TrGUIWindow.i"
	@echo "... src/TrGUI/TrGUIWindow.s"
	@echo "... src/TrGame.o"
	@echo "... src/TrGame.i"
	@echo "... src/TrGame.s"
	@echo "... src/TrGraphics.o"
	@echo "... src/TrGraphics.i"
	@echo "... src/TrGraphics.s"
	@echo "... src/TrMap/TrColorMap.o"
	@echo "... src/TrMap/TrColorMap.i"
	@echo "... src/TrMap/TrColorMap.s"
	@echo "... src/TrMap/TrHeightMap.o"
	@echo "... src/TrMap/TrHeightMap.i"
	@echo "... src/TrMap/TrHeightMap.s"
	@echo "... src/TrMap/TrMap.o"
	@echo "... src/TrMap/TrMap.i"
	@echo "... src/TrMap/TrMap.s"
	@echo "... src/TrMap/TrMapDataUtils.o"
	@echo "... src/TrMap/TrMapDataUtils.i"
	@echo "... src/TrMap/TrMapDataUtils.s"
	@echo "... src/TrMap/TrMoistureMap.o"
	@echo "... src/TrMap/TrMoistureMap.i"
	@echo "... src/TrMap/TrMoistureMap.s"
	@echo "... src/TrMap/TrNormalMap.o"
	@echo "... src/TrMap/TrNormalMap.i"
	@echo "... src/TrMap/TrNormalMap.s"
	@echo "... src/TrMap/TrVegetationMap.o"
	@echo "... src/TrMap/TrVegetationMap.i"
	@echo "... src/TrMap/TrVegetationMap.s"
	@echo "... src/TrMap/TrWaterMap.o"
	@echo "... src/TrMap/TrWaterMap.i"
	@echo "... src/TrMap/TrWaterMap.s"
	@echo "... src/TrMap/TrWindMap.o"
	@echo "... src/TrMap/TrWindMap.i"
	@echo "... src/TrMap/TrWindMap.s"
	@echo "... src/TrRenderLoop/TrGameLoop.o"
	@echo "... src/TrRenderLoop/TrGameLoop.i"
	@echo "... src/TrRenderLoop/TrGameLoop.s"
	@echo "... src/TrRenderLoop/TrMainMenuLoop.o"
	@echo "... src/TrRenderLoop/TrMainMenuLoop.i"
	@echo "... src/TrRenderLoop/TrMainMenuLoop.s"
	@echo "... src/TrRenderLoop/TrTransitionLoop.o"
	@echo "... src/TrRenderLoop/TrTransitionLoop.i"
	@echo "... src/TrRenderLoop/TrTransitionLoop.s"
	@echo "... src/TrUtils/TrMath.o"
	@echo "... src/TrUtils/TrMath.i"
	@echo "... src/TrUtils/TrMath.s"
	@echo "... src/TrUtils/TrSimulation.o"
	@echo "... src/TrUtils/TrSimulation.i"
	@echo "... src/TrUtils/TrSimulation.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/athena.o"
	@echo "... src/athena.i"
	@echo "... src/athena.s"
	@echo "... src/fft.o"
	@echo "... src/fft.i"
	@echo "... src/fft.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

